name: my_yard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Added cupertino_icons
  go_router: ^15.2.0
  shared_preferences: ^2.5.3
  network_info_plus: ^6.1.4
  dart_ping: ^9.0.1
  flutter_riverpod: ^2.6.1 # Use the latest version
  riverpod_annotation: ^2.6.1 # Use the latest version
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^4.0.0 # Use the latest version
  riverpod_generator: ^2.6.5 # Use the latest version
  build_runner: ^2.4.15 # Use the latest version
  json_serializable: ^6.9.5
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/my_yard_name.png" # Path to your master icon
  #min_sdk_android: 21 # Optional: For adaptive icons
  # adaptive_icon_background: "#ffffff" # Optional: For adaptive icons
  # adaptive_icon_foreground: "assets/logo/my_icon_foreground.png" # Optional: For adaptive icons
